
CREATE DATABASE tasklist;

USE tasklist;

CREATE TABLE task (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(950) NOT NULL,
    status VARCHAR(20) NOT NULL,
    responsible VARCHAR(20) NOT NULL,
    createdAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

describe task;